spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/runfengxin/springcloudConfig/
          searchPaths: respo

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/